### ISSUE TITLE
Allow tests to be run on stable compiler

### ISSUE THREAD

**Issue by ebfull** [ebfull/pairing#36]
Right now the benchmarks use unstable compiler APIs, so we need to disable them for the stable compiler.

**Comment by str4d** [comment]
As far as benchmarks go, it seems that the way to achieve the "stable test / nightly bench" split is to [isolate the benchmarks under `benches/`](https://internals.rust-lang.org/t/setting-cfg-nightly-on-nightly-by-default/1893/13). That would require @ebfull to be comfortable with having the benchmarks live a long* way from the code they bench.

Another alternative would be to add a default-off `bench` feature, and gate every single benchmark (or organise them into sub-modules and gate those. There's currently no built-in way to [detect the use of nightly and enable features accordingly](https://internals.rust-lang.org/t/setting-cfg-nightly-on-nightly-by-default/1893), so it would mean running `cargo bench --features bench` perpetually, unless cargo supports defining or overriding commands like npm does?

**Comment by str4d** [comment]
Moving the benchmarks into `benches/` was pretty trivial, and I was able to retain the granularity by emulating the module structure.
