### ISSUE TITLE
Automated performance testing

### ISSUE THREAD

**Issue by ebfull** [ebfull/pairing#6]
Like speed.z.cash.

**Comment by ebfull** [comment]
https://github.com/Electric-Coin-Company/infrastructure/pull/127

**Comment by str4d** [comment]
Benchmarks are now [tracked](https://ci.z.cash/#/builders/15) and [published](https://speed.z.cash/timeline/).

**Comment by ebfull** [comment]
Looks like it's working, thanks @str4d!
