### ISSUE TITLE
some question about bls12-381

### ISSUE THREAD

**Issue by NickyYangYang** [ebfull/pairing#89]
hello, I want to ensure whether the security level of BLS12-381 is 128 bit. 
And  the signature length of  BLS12-381. Is 48 Bytes?

**Comment by ebfull** [comment]
For all practical purposes, BLS12-381 is close to 128-bit security according to current cryptographic research. Technically, NFS can beat BLS12-381 in close to 2<sup>120</sup> work, under some wild conditions that we don't know to be practical at this time. Most curves that target the 128-bit security level don't actually reach or exceed that level for various reasons; our goal is to get "close enough" within reason, considering space and time requirements for known attacks, and the performance tradeoffs. As an example, Curve25519 technically only has 125-bit security against Pollard rho, which is neither here nor there.

BLS12-381 compressed group elements have the following size:

* G1 = 48 bytes
* G2 = 96 bytes

In the BLS signature scheme you can use either G1 or G2 for signatures depending on what you need.
